name: Generate Contribution Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Generate snake
        uses: Platane/snk@v3
        with:
          github_user_name: aaravgoel2209
          outputs: |
            snake-output/github-contribution-grid-snake.svg
            snake-output/github-contribution-grid-snake-dark.svg

      - name: Push snake to repo
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: main
          build_dir: snake-output
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
